name: CI

on: [push, pull_request]

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        node:
          - '18.12'
          - '20'
          - '22'
        platform:
          - ubuntu-latest

    name: '${{matrix.platform}} / Node.js ${{ matrix.node }}'
    runs-on: ${{matrix.platform}}

    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          standalone: true
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
      - name: Install npm@8
        run: pnpm add --global npm@8
      - name: pnpm install
        run: pnpm install
      - name: Audit
        run: pnpm audit
      - name: build
        run: pnpm run build
      - name: test
        run: pnpm run test
